version: '3'

services:
  telegram-bot:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - telegram_bot/.env
    volumes:
      - ./telegram_bot:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s