services:
  - type: web
    name: chatgpt-claude-mistral-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_application.wsgi
    envVars:
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: WEBHOOK_URL
        value: https://flask-53nr.onrender.com/
    healthCheckPath: /health
    healthCheckTimeout: 5
    autoDeploy: true